#!/usr/bin/python

import time;
import sys

import RPi.GPIO as GPIO
from perlish import *

GPIO.setmode(GPIO.BCM)

pinR = [5,6,13];
pinC = [26,7,12,16];


def setup():
    for r in range(0,3):
        printf("setup R %d OUT\n", pinR[r]);
        GPIO.setup(pinR[r], GPIO.OUT)
        GPIO.output(pinR[r], 1);
        
    for c in range(0,4):
        printf("setup C %d IN\n", pinC[c]);
        GPIO.setup(pinC[c], GPIO.IN);

def read_row(r):
    cbits = 0;
    GPIO.output(pinR[r], 0);
    for c in range(0,4):
        cbits <<= 1;
        cbits |= GPIO.input(pinC[c]);
    GPIO.output(pinR[r], 1);
    return cbits;


def read_raw():
    rawbits = 0;
    for r in range(0,3):
        rawbits <<= 4;
        rawbits |= read_row(r);
    return rawbits;


setup();

oldbits = 0xfff;

nloops=1000;
tstart = time.time();
for i in range(0,nloops):
    keybits = read_raw();
    oldbits = keybits;
tend = time.time();
ttime = tend-tstart;

printf("%d loops in %f sec; %f/sec\n", nloops, ttime, nloops/ttime);

while(True):
    keybits = read_raw();
    if(keybits != oldbits):
        printf("keybits: %03x  %03x\n", keybits, keybits ^ oldbits);
        oldbits = keybits;
    time.sleep(0.010);
