#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
import os
import pprint
import time;
import signal;
from perlish import *

import RPi.GPIO as GPIO
from SgtMatrixKBD import SgtMatrixKBD;
from SgtStationList import SgtStationList;
from SgtNetInfo import SgtNetInfo
from mpd import (MPDClient, CommandError)
from socket import error as SocketError
from Adafruit_CharLCD import Adafruit_CharLCD

HOST = 'localhost'
PORT = '6600'
PASSWORD = False

##
CON_ID = {'host':HOST, 'port':PORT}
##  

verbose = False;

mpd = False;
lcd = False;
backlight_gpio = 24;

## Some functions
def mpdConnect(client, con_id):
    try:
        client.connect(**con_id)
    except SocketError:
        return False
    return True

def mpdAuth(client, secret):
    try:
        client.password(secret)
    except CommandError:
        return False
    return True

def mpdSetup():
    client = MPDClient()
    if mpdConnect(client, CON_ID):
        print('Got connected!')
    else:
        print('fail to connect MPD server.')
        return False
    # Auth if password is set non False
    if PASSWORD:
        if mpdAuth(client, PASSWORD):
            print('Pass auth!')
        else:
            print('Error trying to pass auth.')
            client.disconnect()
            return False

    return client;

def mpdStateDiff(st, pst):
    if(type(st) != type(pst)):
        print("mpdStateDiff type")
        return True;
    if(st['state'] != pst['state']):
        print("mpdStateDiff state")
        return True;

    if(('song' in st) != ('song' in pst)):
        print("mpdStateDiff songkey")
        return True;
    
    if('song' in st and 'song' in pst
       and st['song'] != pst['song']):
        print("mpdStateDiff song")
        song = st['song']
        printf("song: %s\n", str(song));
        return True;
        
    if(('songid' in st) != ('songid' in pst)):
        print("mpdStateDiff songid key")
        return True;

    if('songid' in st != 'songid' in pst
       and st['songid'] != pst['songid']):
        print("mpdStateDiff songid")
        return True

    else:
        return False

class SbStatus:
   def  __init__(self):
       self.restarting = 0;
       self.p_mstatus  = None;   # mpd.status() result
       self.mstatus  = None;   # mpd.status() result
       self.msong    = None;  # mpd.currentsong() result
       self.presetbank = 0;

   def update_from_mpd(self):
       self.p_mstatus = self.mstatus;
       self.mstatus = mpd.status();
       if(self.mstatus['state']== 'play'):
           self.msong = mpd.currentsong();
       else:
           self.msong = dict();

   def clear_state(self):
       self.msong = None;
       self.mstatus = None;
           
   def bank_increment(self):
       if(self.presetbank == 3):
           self.presetbank = 0;
       else:
           self.presetbank += 1;
       printf("presetbank=%d\n", self.presetbank);

class SgtSBDisplay:
    """Manage the Audio Stream Box lcd display"""
    def __init__(self, lcd, sbstat, sl, backlight_gpio=24):
        self.lcd = lcd;
        self.sl = sl;
        self.sbstat = sbstat;
        self.t_lastupdate = 0; 
        self.verbose = False;
        self.npstbuttons = 8;
        self.prev_lcd_status = "";
        self.last_presetbank = sbstat.presetbank;
        self.dispmode = 0;
        self.last_dispmode = 0;
        self.backlight_gpio = backlight_gpio
        GPIO.setup(backlight_gpio, GPIO.OUT)
        self.backlight(0);
        self.playing = False
        self.t_backlighttime = 0;
        self.netinf = SgtNetInfo()

    def backlight(self, onoff):
        GPIO.output(self.backlight_gpio, onoff)
        
    def signon(self):
        self.lcd.begin(40, 2)
        self.lcd.clear()
        self.lcd.message("Streambox by telltronics");
        self.backlight(1);
        self.t_backlighttime = time.time()

    def fail_message(self, s):
        self.lcd.setCursor(0, 0);  # col,row
        self.lcd.message(s);
        printf(s);
    
    def update(self):
        t_now = time.time();
        if(t_now - self.t_lastupdate > 5
           or mpdStateDiff(self.sbstat.mstatus, self.sbstat.p_mstatus)
           or self.last_dispmode != self.dispmode):
            self.draw_lcd_top();
            self.t_lastupdate = t_now;
            self.last_dispmode = self.dispmode;
        if(self.last_presetbank != self.sbstat.presetbank):
            self.draw_lcd_bottom();
            self.last_presetbank = self.sbstat.presetbank;
            
        if(self.playing):
            self.backlight(1)
            self.t_backlighttime = t_now
        else:
            if(t_now - self.t_backlighttime > 5):
                self.backlight(0)
    
    def draw_lcd_top(self):
        self.lcd.setCursor(0, 0);
        s = self.build_top_string();
        s = sprintf("%-40.40s", s);
        lcd.message(s);

    def build_top_string(self):
        if(self.dispmode >= 0 and self.dispmode <= 3):
            return self.build_status_string(self.dispmode)
        elif(self.dispmode == 4):
            s = self.build_myurl_string()
            printf("my URL: %s\n", s) 
            return s
        else:
            return sprintf("dispmode %d?", self.dispmode)

    def build_status_string(self, dispmode):
        nt = '';
        st = self.sbstat.mstatus;
        if('error' in st):
            nt = "ERR:"+st['error'];
            self.playing = False
        else:
            if(st['state'] == 'stop'):
                nt = '[stopped]';
                self.playing = False
            if(st['state'] == 'pause'):
                nt = '[pause]';
                self.playing = False
            elif(st['state']== 'play'):
                self.playing = True
                song = self.sbstat.msong;
                nt = '';
                if(dispmode == 0):
                    if('name' in song):
                        nt += song['name'];
                    if(len(nt) > 1):
                        nt += " "
                    if('title' in song):
                        nt += song['title'];
                elif(dispmode == 1):
                    if('name' in song):
                        nt += song['name'];
                elif(dispmode == 2):
                    if('title' in song):
                        nt += song['title'];
                elif(dispmode == 3):
                    if('file' in song):
                        nt += song['file'];

                if(len(nt) < 1):
                    nt = sprintf("%s:%s", song['id'], song['file']);
            
        #s = sprintf("%-40.40s", nt);
        s = nt
        if(s != self.prev_lcd_status or self.verbose):
            printf("status:\"%s\"\n", s);
            printf("  song: %s\n", str(self.sbstat.msong));
            self.prev_lcd_status = s;
        return s;

    def build_myurl_string(self):
        self.netinf.getinfo()
        if(self.netinf.up):
            return sprintf("http://%-32.32s", self.netinf.ipaddr)
        else:
            return "no network connection!"
        
    def dispmode_increment(self):
       if(self.dispmode == 5):
           self.dispmode = 0;
       else:
           self.dispmode += 1;
       printf("dispmode=%d\n", self.dispmode);

    def draw_lcd_bottom(self):
        self.lcd.setCursor(0, 1);
        for i in range(0, self.npstbuttons):
            sno = self.sbstat.presetbank * self.npstbuttons + i;
            callstr = self.sl.calli(sno);
            if(callstr == None):
                callstr = '----';
            self.lcd.message( sprintf("%4s ", callstr));
            if(i==3):
                self.lcd.message(" ");

def handle_buttons(keys, sbstat, disp, sl):
    global mpd;
    state = sbstat.mstatus['state'];
    for k in keys:	# note each key event is a string
        if(k == 'P'):
            if('error' in sbstat.mstatus):
                printf("error state: trying pulse+mpd restart");
                disp.fail_message("restarting; stand by...  ");

                mpd.close();
                sbstat.clear_state();
#                os.system("service mpd stop");
#                os.system("service mpd start");
                mpd = mpdSetup();
                return;

            if(state != 'stop'):
                printf("poweroff\n");
                mpd.stop();
                sbstat.clear_state();
            else:
                printf("poweron.  todo: resume last stream\n");

        elif(k == 'B'):
            sbstat.bank_increment();

        elif(k == 'D'):
            disp.dispmode_increment();
                
        elif(k >= '1' and k <= '8'):
            pst = int(k) - 1 + sbstat.presetbank * disp.npstbuttons;
            scall = sl.calli(pst);
            printf("key %s; change to preset %d %s\n", k, pst, str(scall));
            if(scall):
                mpd.play(pst);
        else:
            if(k[0] != '!'):
                printf("key %s unbound\n", k);

        sys.stdout.flush()

# signal handler
def clean_exit(signal, frame):
    printf("\nsig %s caught!\n", str(signal) );
    lcd.begin(40, 2)
    lcd.clear()
    lcd.message("streambox halted");
    GPIO.output(backlight_gpio, 0)
    sys.exit(0);

def main():
    global mpd;
    global lcd;
    sbstat = SbStatus();
    kb = SgtMatrixKBD(pin_rows = [5,6,13],
                      pin_columns = [16, 12, 7, 26]);
    sl = SgtStationList();
    sl.initfixed();
    lcd = Adafruit_CharLCD(pin_rs=17,
                       pin_e=27,
                       pins_db=[22,10,9,11]);

    disp = SgtSBDisplay(lcd, sbstat, sl, backlight_gpio=backlight_gpio);
    disp.signon();
    
    signal.signal(signal.SIGINT, clean_exit);
    signal.signal(signal.SIGTERM, clean_exit);

    mpd = mpdSetup();
    if(not mpd):
        disp.fail_message("MPD connect failed.");
        sys.exit(1);
    mpd.stop();
    mpd.consume(0);
    mpd.single(1);

    printf("connected");
    sl.mpdplaylist(mpd);
    sl.mpdchecklist(mpd);
    disp.draw_lcd_bottom();

    sbstat.update_from_mpd();

    disp.update();
    while(True):
        keys = kb.poll();
        if(len(keys)>0):
            handle_buttons(keys, sbstat, disp, sl);

        sbstat.update_from_mpd();
        disp.update();

def iotest_main():  # too much of this duplicates main(); TODO: refactor.
    global lcd;
    signal.signal(signal.SIGINT, clean_exit);
    signal.signal(signal.SIGTERM, clean_exit);
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(backlight_gpio, GPIO.OUT)
    GPIO.output(backlight_gpio, 1);
    
    kb = SgtMatrixKBD(pin_rows = [5,6,13],
                      pin_columns = [16, 12, 7, 26]);
    lcd = Adafruit_CharLCD(pin_rs=17,
                       pin_e=27,
                       pins_db=[22,10,9,11]);
    lcd.begin(40, 2)
    lcd.setCursor(0, 0);  # col,row
    printf("sgt streambox matrix keypad test\n")
    lcd.message("sgt streambox matrix keypad test")
    while(True):
        keycodes = kb.poll_keycodes()
        for kc in keycodes:
            sym = kb.code_to_symbol(kc)
            printf("0x%02x   %s\n", kc, str(sym))
            msg = sprintf("0x%02x  %s     ", kc, str(sym))
            lcd.setCursor(0, 1);  # col,row
            lcd.message(msg)
    
        
# Script starts here
if __name__ == "__main__":
    if(len(sys.argv) >= 2 and sys.argv[1] == "--iotest"):
        iotest_main()
    else:
        main()
